# Generated by Django 3.0.4 on 2020-03-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='employee',
            name='email_address',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
